pub mod accounting;
pub mod agriculture;
pub mod construction;
pub mod education;
pub mod hr;
pub mod legal;
pub mod medical;
pub mod real_estate;
pub mod registry;
pub mod supply_chain;

pub use accounting::AccountingEngine;
pub use agriculture::AgricultureAssistant;
pub use construction::ConstructionManager;
pub use education::EducationAssistant;
pub use hr::HRManager;
pub use legal::LegalSuite;
pub use medical::MedicalAssistant;
pub use real_estate::RealEstateAgent;
pub use registry::{IndustryVertical, VerticalRegistry};
pub use supply_chain::SupplyChainManager;
